name: "Pull Request Labeler"

on:
  workflow_dispatch:
     inputs:
      PARENT_SHA:
        description: "Parent Workflow SHA"
        required: true

permissions:
  contents: read

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: srvaroa/labeler@e216fb40e2e6d3b17d90fb1d950f98bee92f65ce # master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout specific commit from Parent Workflow
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.PARENT_SHA }}

      - name: Create Completion Flag
        run:  echo "Labeler workflow completed" > LABELER_flag_${{ github.event.inputs.PARENT_SHA }}.txt


      - name: Upload completion artifact
        uses: actions/upload-artifact@v4
        with:
          name: workflow-LABELER-completed_${{ github.event.inputs.PARENT_SHA }}
          path: LABELER_flag_${{ github.event.inputs.PARENT_SHA }}.txt
