name: "Pull Request Labeler"

on:
  workflow_call:
    inputs:
      artifact_id:
        description: 'Unique identifier for artifacts'
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      # Step 1: Harden the runner
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      # Step 2: Run the labeler
      - name: Apply Labels to Pull Request
        id: label_step
        uses: srvaroa/labeler@e216fb40e2e6d3b17d90fb1d950f98bee92f65ce # master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # Step 3: Generate label artifact
      - name: Generate label artifact
        run: |
          echo "Generating label artifact with meaningful data..."
          mkdir -p labeler

          echo "Workflow Name: Pull Request Labeler" > labeler/labeler.txt
          echo "Artifact ID: ${{ inputs.artifact_id }}" >> labeler/labeler.txt

          if [[ -n "${{ steps.label_step.outputs.labels }}" ]]; then
            echo "Labels Applied:" >> labeler/labeler.txt
            echo "${{ steps.label_step.outputs.labels }}" >> labeler/labeler.txt
          else
            echo "No labels were applied." >> labeler/labeler.txt
          fi

      # Step 4: Upload the artifact
      - name: Upload label artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_id }}
          path: labeler/
