name: Parent Workflow
#test 
on: 
  pull_request:
  push: 
    branches:
      - develop
      - main
      - custom_validators_nils

permissions:
  contents: write
  pages: write
  pull-requests: write
  id-token: write
  security-events: write
  workflow_run: write

jobs:
  hello-world:
    name: "Hello World"
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: echo "Hello World"
